version: '3.4'

services:
  smartapartmententerprise:
    image: ${DOCKER_REGISTRY-}smartapartmententerprisespa
    build:
      context: .
      dockerfile: Web/SmartApartmentEnterprise.SPA/Dockerfile
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/app/ClientApp/node_modules/@angular/cli/bin/

  propertymanagement:
    image: ${DOCKER_REGISTRY-}propertymanagementapi
    build:
      context: .
      dockerfile: Services/PropertyManagement/PropertyManagement.API/Dockerfile

  identity:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: Services/Identity/Identity.API/Dockerfile

