version: '3.4'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
  smartapartmententerprise:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "44358:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  propertymanagement:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - AUTH_URL=http://host.docker.internal:5000
      - AUTH_URL_CLIENT=https://localhost:5001
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - WEBAPP_URL=https://localhost:44358
    ports:
      - "80"
      - "44309:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    #depends_on:
    #    - elasticsearch

  identity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - PROPERTYMANAGEMENTSWAGGERCLIENT=https://localhost:44309
      - PROPERTYMANAGEMENT_URL=http://propertymanagement
      - WEBAPP_URL=https://localhost:44358
    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
